In [1]:
from datafetcher import EliaTotalLoadForecastFetcher, EliaWindFetcher, EliaSolarFetcher, ElexysBelpexFetcher
import datetime as dt

In [8]:
# the first time you use a DataFetcher sub class, it will download some cached data from Dropbox (around 20MB)
# this might take a while depending on your connection speed
df_solar = EliaSolarFetcher().fetch()
df_solar.head()
df_solar.tail()
#df_solar.DayAheadForecast[df_solar.index > dt.datetime.now()-dt.timedelta(weeks=1)].plot()

,DayAheadForecast,LoadFactor,MonitoredCapacity,MostRecentForecast,WeekAheadForecast
2018-04-30 20:45:00,NaN,NaN,3369.05,0.0,NaN
2018-04-30 21:00:00,NaN,NaN,3369.05,0.0,NaN
2018-04-30 21:15:00,NaN,NaN,3369.05,0.0,NaN
2018-04-30 21:30:00,NaN,NaN,3369.05,0.0,NaN
2018-04-30 21:45:00,NaN,NaN,3369.05,0.0,NaN

In [17]:
df_load = EliaTotalLoadForecastFetcher().fetch()
df_load.tail()

                       value
2018-04-23 22:45:00  9856.00
2018-04-23 23:00:00  9765.39
2018-04-23 23:15:00  9685.64
2018-04-23 23:30:00  9497.07
2018-04-23 23:45:00  9351.28

In [9]:
df_belpex = ElexysBelpexFetcher().fetch()
df_belpex.head()

                     price
2018-04-24 23:00:00  40.18
2018-04-24 22:00:00  44.90
2018-04-24 21:00:00  47.09
2018-04-24 20:00:00  47.94
2018-04-24 19:00:00  46.39

In [11]:
# the Elia Wind API is extremely slow, so in this example we only use cached data
df_wind = EliaWindFetcher(only_cached=True).fetch()
df_wind.tail()

,DayAheadConfidence10,DayAheadConfidence90,DayAheadForecast,LoadFactor,MonitoredCapacity,MostRecentForecast,Realtime,WeekAheadConfidence10,WeekAheadConfidence90
2018-04-30 20:45:00,NaN,NaN,NaN,NaN,2767.11,765.87,NaN,NaN,NaN
2018-04-30 21:00:00,NaN,NaN,NaN,NaN,2767.11,768.92,NaN,NaN,NaN
2018-04-30 21:15:00,NaN,NaN,NaN,NaN,2767.11,772.18,NaN,NaN,NaN
2018-04-30 21:30:00,NaN,NaN,NaN,NaN,2767.11,775.44,NaN,NaN,NaN
2018-04-30 21:45:00,NaN,NaN,NaN,NaN,2767.11,778.70,NaN,NaN,NaN